# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: cramsay homepage
email: craig.ramsay.100@strath.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  cramsay homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "cramsay.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: thecramsay
github_username:  cramsay

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console@v0.3.12
# theme: jekyll-theme-console
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - frame-game.md
footer: '<a href="https://github.com/cramsay">github</a> <a href="https://researchportal.hw.ac.uk/en/persons/craig-ramsay/">heriot-watt</a> <a href="https://pureportal.strath.ac.uk/en/persons/craig-ramsay/">strathclyde</a>'
listen_for_clients_preferred_style: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
